version: "3.8"

services:
  # --------------------
  # MinIO
  # --------------------
  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "dthuadmin"
      MINIO_ROOT_PASSWORD: "SuperStrongPwd123!"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  # --------------------
  # MongoDB
  # --------------------
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 19006292
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db

  # --------------------
  # Zookeeper (for Kafka)
  # --------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # --------------------
  # Kafka broker
  # --------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --------------------
  # Elasticsearch
  # --------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=MyStrongPassword123
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # --------------------
  # Service example using Elasticsearch ENV
  # --------------------
  app-service:
    image: your-app-image
    depends_on:
      - elasticsearch
    environment:
      ES_ADDRESSES: "https://elasticsearch:9200"
      ES_USER: "elastic"
      ES_PASSWORD: "MyStrongPassword123"

volumes:
  esdata:
